{% set name = "psygnal" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f64f62dee2306fc1c22050a59b6c6cdad126e04b0cf50e393ff858a1da719096

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python

test:
  imports:
    - psygnal
    - psygnal.containers
    - psygnal.utils
  requires:
    - pip
    - typing_extensions
  commands:
    - pip check

about:
  home: https://github.com/pyapp-kit/psygnal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure python implementation of Qt Signals
  description: |
    Psygnal is a pure python implementation of Qt Signals. It is designed to be
    a drop-in replacement for PyQt/PySide signals, but with a few extra features
    and a few less bugs.
  doc_url: https://psygnal.readthedocs.io/
  dev_url: https://github.com/pyapp-kit/psygnal

extra:
  recipe-maintainers:
    - tlambert03
