{% set name = "psygnal" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d2a99803f3152c469d3642d36c04d680213a20e114245558e026695adf9a9c2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python
    - typing_extensions  # not actually required at runtime
    - wrapt  # provides 'proxy' extra

# typing_extensions is not actually required at runtime, but is required for
# type checking. It is included here to ensure that it is installed when
# running tests.

test:
  imports:
    - psygnal
    - psygnal.containers
    - psygnal.utils
  requires:
    - pip
    - python
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/psygnal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure python implementation of Qt Signals
  description: |
    Psygnal is a pure python implementation of Qt Signals. It is designed to be
    a drop-in replacement for PyQt/PySide signals, but with a few extra features
    and a few less bugs.
  doc_url: https://psygnal.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/psygnal

extra:
  recipe-maintainers:
    - tlambert03
