{% set name = "psygnal" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a42cd3e55c474673cc8f61e7cdb40fb647ca94868a1d262bf4b6d6aa2fc8bf27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python >=3.7
    - typing_extensions
    - mypy_extensions
    - wrapt  # provides 'proxy' extra
    - importlib-metadata >=1.5.0

test:
  imports:
    - psygnal
    - psygnal.containers
    - psygnal.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/psygnal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure python implementation of Qt Signals
  doc_url: https://psygnal.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/psygnal

extra:
  recipe-maintainers:
    - tlambert03
