{% set name = "psygnal" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9b02ca246ab0adb108c4010b4a486e464f940543201074591e50370cd7b0cc0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python >=3.8
    - typing_extensions  # not actually required at runtime
    - wrapt  # provides 'proxy' extra

test:
  imports:
    - psygnal
    - psygnal.containers
    - psygnal.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/psygnal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure python implementation of Qt Signals
  doc_url: https://psygnal.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/psygnal

extra:
  recipe-maintainers:
    - tlambert03
