{% set name = "psygnal" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10399186ec18fc3d8d985592ad38cfe3440b7a74de16fac882ede7a79644e8df

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.0a10                      # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=3.0.0a10
    - setuptools_scm
  run:
    - python
    - typing-extensions
    - wrapt  # provides 'proxy' extra

test:
  imports:
    - psygnal
    - psygnal.containers
    - psygnal.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/psygnal
  license: BSD-3-Clause
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
  license_family: BSD
  license_file: LICENSE
  summary: Pure python implementation of Qt Signals

extra:
  recipe-maintainers:
    - tlambert03
